import sqlite3
conn = sqlite3.connect('vendas_ficticias.db')
cursor = conn.cursor()
cursor.execute('SELECT name FROM sqlite_master WHERE type="table"')
tables = cursor.fetchall()
print("Tables:", tables)
cursor.execute('SELECT COUNT(*) FROM vendas')
count = cursor.fetchone()
print("Rows in vendas:", count[0])
conn.close()